#!/bin/bash
env_re="(.*)X_SSH_ORIGINAL_COMMAND=([a-zA-Z0-9_]+|\"(([^\"\\]+|\\.)*)\")[[:space:]]*(.*)"
if [[ $SSH_ORIGINAL_COMMAND =~ $env_re ]]; then
	if [ "${BASH_REMATCH[3]}" -o "${BASH_REMATCH[2]}" = "\"\"" ]; then
		X_SSH_ORIGINAL_COMMAND="${BASH_REMATCH[3]}"
	else
		X_SSH_ORIGINAL_COMMAND="${BASH_REMATCH[2]}"
	fi
	SSH_ORIGINAL_COMMAND="${BASH_REMATCH[1]}${BASH_REMATCH[5]}"
fi

ORIGCMD=$SSH_ORIGINAL_COMMAND
if [ "${X_SSH_ORIGINAL_COMMAND}" ]; then
	export SSH_ORIGINAL_COMMAND="${X_SSH_ORIGINAL_COMMAND}"
else
	unset SSH_ORIGINAL_COMMAND
fi

$ORIGCMD
